#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
from mtparse import *

def main(argv):
	if len(argv) == 2:
		filename = argv[1]
#		print 'Trying to read config file: %s' % filename
		config = read_config(filename)

		if not config:
#			print 'Error reading %s' % filename
			exit(1)

		for secret in read_section(config, '/ppp secret'):
			d = line_dict(secret)
			if 'name' in d and 'password' in d and 'service' in d:
				print '%s:%s:%s' % (d['service'], d['name'], d['password'])
			elif 'name' in d and 'password' in d:
				print 'any:%s:%s' % (d['name'], d['password'])


if __name__ == '__main__':
	main(sys.argv)

