#!/bin/bash
THREADDIR=`mktemp -d`
MAXTHREADS=20
PID=1
LOG="winbox-list-mt.log"

usage()  {
	echo "Usage: `basename $0` <list-file> <login> <password>"
	exit 0
}

[ "$2" == "" ] && usage

if [ ! -f "$1" ]; then
	echo "Can't open file $1"
	exit 1
fi

for ip in $(cat "$1"); do
	while [ -f $THREADDIR/$PID ]; do
		if [ $PID -eq $MAXTHREADS ]; then
			PID=0
		fi
		sleep .25
		PID=$[$PID+1]
	done

	touch "$THREADDIR/$PID"
	{
expect <<END
set timeout 10
spawn wine /root/bin/winbox.exe $ip $2 "$3"
expect "logged in!!!" { puts [open $LOG a+] "$2@$ip:$3" }
END
		rm "$THREADDIR/$PID"
	} &
done





